apiVersion: cce.huaweicloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    containerNetworkType: overlay_l2
    flavorId: cce.s1.small
    name: cluster
    subnetId: ${huaweicloud_vpc_subnet.mysubnet.id}
    vpcId: ${huaweicloud_vpc.myvpc.id}
