apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/user
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: A user
    name: user_1
    passwordSecretRef:
      key: password
      name: user-secret
      namespace: crossplane-system
