apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: UserToken
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/usertoken
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accountName: hwstaff_zhenguo
    passwordSecretRef:
      key: password
      name: user-secret
      namespace: crossplane-system
    userName: user_1
