apiVersion: cce.huaweicloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.crossplane.io/example-id: cce/v1alpha1/cluster
  labels:
    testing.crossplane.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    containerNetworkType: overlay_l2
    flavorId: cce.s1.small
    name: cluster
    subnetId: example_subnet_id
    vpcId: example_vpc_id
