apiVersion: cce.huaweicloud.crossplane.io/v1alpha1
kind: Node
metadata:
  annotations:
    meta.crossplane.io/example-id: cce/v1alpha1/node
  labels:
    testing.crossplane.io/example-name: node
  name: node
spec:
  forProvider:
    availabilityZone: cn-north-4a
    clusterIdSelector:
      matchLabels:
        testing.crossplane.io/example-name: cluster
    dataVolumes:
    - size: 100
      volumetype: SSD
    flavorId: flavor-id
    keyPair: keypair-name
    name: example
    rootVolume:
    - size: 40
      volumetype: SSD
