apiVersion: geminidb.huaweicloud.crossplane.io/v1alpha1
kind: RedisInstance
metadata:
  annotations:
    meta.upbound.io/example-id: geminidb/v1alpha1/redisinstance
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    flavor: geminidb.redis.xlarge.4
    name: gaussdb_redis_instance_1
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      foo: bar
      key: value
    volumeSize: 16
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
