// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PrivateGatewayInitParameters struct {

	// Specifies the description of the private NAT gateway, which contain maximum of
	// 255 characters, and angle brackets (< and >) are not allowed.
	// The description of the private NAT gateway.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the ID of the enterprise project to which the private
	// NAT gateway belongs.
	// Changing this will create a new resource.
	// The ID of the enterprise project to which the private NAT gateway belongs.
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	// Specifies the private NAT gateway name.
	// The valid length is limited from 1 to 64, only English letters, Chinese characters, digits, hyphens (-) and
	// underscores (_) are allowed.
	// The name of the private NAT gateway.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the region where the private NAT gateway is located.
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	// The region where the private NAT gateway is located.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the specification of the private NAT gateway.
	// The valid values are as follows:
	// The specification of the private NAT gateway.
	Spec *string `json:"spec,omitempty" tf:"spec,omitempty"`

	// Specifies the network ID of the subnet to which the private NAT gateway
	// belongs.
	// Changing this will create a new resource.
	// The network ID of the subnet to which the private NAT gateway belongs.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/vpc/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.Reference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.Selector `json:"subnetIdSelector,omitempty" tf:"-"`

	// Specifies the key/value pairs to associate with the private NAT gateway.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type PrivateGatewayObservation struct {

	// The creation time of the private NAT gateway.
	// The creation time of the private NAT gateway.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Specifies the description of the private NAT gateway, which contain maximum of
	// 255 characters, and angle brackets (< and >) are not allowed.
	// The description of the private NAT gateway.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the ID of the enterprise project to which the private
	// NAT gateway belongs.
	// Changing this will create a new resource.
	// The ID of the enterprise project to which the private NAT gateway belongs.
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	// The resource ID in UUID format.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the private NAT gateway name.
	// The valid length is limited from 1 to 64, only English letters, Chinese characters, digits, hyphens (-) and
	// underscores (_) are allowed.
	// The name of the private NAT gateway.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the region where the private NAT gateway is located.
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	// The region where the private NAT gateway is located.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the specification of the private NAT gateway.
	// The valid values are as follows:
	// The specification of the private NAT gateway.
	Spec *string `json:"spec,omitempty" tf:"spec,omitempty"`

	// The current status of the private NAT gateway.
	// The current status of the private NAT gateway.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Specifies the network ID of the subnet to which the private NAT gateway
	// belongs.
	// Changing this will create a new resource.
	// The network ID of the subnet to which the private NAT gateway belongs.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Specifies the key/value pairs to associate with the private NAT gateway.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// The latest update time of the private NAT gateway.
	// The latest update time of the private NAT gateway.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// The ID of the VPC to which the private NAT gateway belongs.
	// The ID of the VPC to which the private NAT gateway belongs.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type PrivateGatewayParameters struct {

	// Specifies the description of the private NAT gateway, which contain maximum of
	// 255 characters, and angle brackets (< and >) are not allowed.
	// The description of the private NAT gateway.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the ID of the enterprise project to which the private
	// NAT gateway belongs.
	// Changing this will create a new resource.
	// The ID of the enterprise project to which the private NAT gateway belongs.
	// +kubebuilder:validation:Optional
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	// Specifies the private NAT gateway name.
	// The valid length is limited from 1 to 64, only English letters, Chinese characters, digits, hyphens (-) and
	// underscores (_) are allowed.
	// The name of the private NAT gateway.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the region where the private NAT gateway is located.
	// If omitted, the provider-level region will be used. Changing this will create a new resource.
	// The region where the private NAT gateway is located.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the specification of the private NAT gateway.
	// The valid values are as follows:
	// The specification of the private NAT gateway.
	// +kubebuilder:validation:Optional
	Spec *string `json:"spec,omitempty" tf:"spec,omitempty"`

	// Specifies the network ID of the subnet to which the private NAT gateway
	// belongs.
	// Changing this will create a new resource.
	// The network ID of the subnet to which the private NAT gateway belongs.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/vpc/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.Reference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in vpc to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.Selector `json:"subnetIdSelector,omitempty" tf:"-"`

	// Specifies the key/value pairs to associate with the private NAT gateway.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// PrivateGatewaySpec defines the desired state of PrivateGateway
type PrivateGatewaySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrivateGatewayParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrivateGatewayInitParameters `json:"initProvider,omitempty"`
}

// PrivateGatewayStatus defines the observed state of PrivateGateway.
type PrivateGatewayStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrivateGatewayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrivateGateway is the Schema for the PrivateGateways API. Manages a gateway resource of the
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type PrivateGateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PrivateGatewaySpec   `json:"spec"`
	Status PrivateGatewayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrivateGatewayList contains a list of PrivateGateways
type PrivateGatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivateGateway `json:"items"`
}

// Repository type metadata.
var (
	PrivateGateway_Kind             = "PrivateGateway"
	PrivateGateway_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrivateGateway_Kind}.String()
	PrivateGateway_KindAPIVersion   = PrivateGateway_Kind + "." + CRDGroupVersion.String()
	PrivateGateway_GroupVersionKind = CRDGroupVersion.WithKind(PrivateGateway_Kind)
)

func init() {
	SchemeBuilder.Register(&PrivateGateway{}, &PrivateGatewayList{})
}
