apiVersion: kafka.huaweicloud.crossplane.io/v1alpha1
kind: KafkaTopic
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/kafkatopic
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: topic_1
    partitions: 20
