apiVersion: kafka.huaweicloud.crossplane.io/v1alpha1
kind: KafkaUserPasswordReset
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/kafkauserpasswordreset
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    newPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    userName: ${var.user_name}
