apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: Parametergroup
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/parametergroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    datastore:
    - type: mysql
      version: "5.6"
    description: description_1
    name: test_name
    values:
      autocommit: "OFF"
      max_connections: "10"
