apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: GlobalInternetBandwidth
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/globalinternetbandwidth
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessSite: your_access_site
    chargeMode: 95peak_guar
    enterpriseProjectId: your_enterprise_project_id
    isp: your_isp
    name: test
    size: 300
    tags:
      foo: bar
      key: value
    type: your_allowed_bandwidth_type
