apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: GlobalEipAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/globaleipassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    associateInstance:
    - instanceId: your_instance_id
      instanceType: ECS
      projectId: your_project_id
      region: your_region
    gcBandwidth:
    - chargeMode: bwd
      name: your_gc_bandwidth_name
      size: 5
    globalEipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    isReserveGcb: false
