apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: VpcEipAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/vpceipassociate
  labels:
    testing.upbound.io/example-name: associated
  name: associated
spec:
  forProvider:
    fixedIp: 192.168.0.196
    networkId: 828907cc-40c9-42fe-8206-ecc1bdd30060
    publicIp: 121.36.45.205
    portId: ""
