apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: VpcEipV3Associate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/vpceipv3associate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    associateInstanceId: b28cf22e-e0a2-4347-bc8e-f927c9c61332
    associateInstanceType: PORT
    publicipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: dedicated
