// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this DashboardWidget.
func (mg *DashboardWidget) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DashboardID),
		Extract:      resource.ExtractResourceID(),
		Reference:    mg.Spec.ForProvider.DashboardIDRef,
		Selector:     mg.Spec.ForProvider.DashboardIDSelector,
		To: reference.To{
			List:    &DashboardList{},
			Managed: &Dashboard{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DashboardID")
	}
	mg.Spec.ForProvider.DashboardID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DashboardIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DashboardID),
		Extract:      resource.ExtractResourceID(),
		Reference:    mg.Spec.InitProvider.DashboardIDRef,
		Selector:     mg.Spec.InitProvider.DashboardIDSelector,
		To: reference.To{
			List:    &DashboardList{},
			Managed: &Dashboard{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DashboardID")
	}
	mg.Spec.InitProvider.DashboardID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DashboardIDRef = rsp.ResolvedReference

	return nil
}
