apiVersion: modelarts.huaweicloud.crossplane.io/v1alpha1
kind: DatasetVersion
metadata:
  annotations:
    meta.upbound.io/example-id: modelarts/v1alpha1/datasetversion
  labels:
    testing.upbound.io/example-name: v001
  name: v001
spec:
  forProvider:
    datasetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Created by demo
    name: v001
