// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ReadReplicaInstanceDBInitParameters struct {

	// Specifies the database port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type ReadReplicaInstanceDBObservation struct {

	// Specifies the database port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specifies the volume type. It must same with the type of the primary instance.
	// Its value can be any of the following and is case-sensitive:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Specifies the DB instance name. The DB instance name of the same type must be
	// unique for the same tenant. The value must be 4 to 64 characters in length and start with a letter. It is
	// case-sensitive and can contain only letters, digits, hyphens (-), and underscores (_). Changing this parameter will
	// create a new resource.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ReadReplicaInstanceDBParameters struct {

	// Specifies the database port.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type ReadReplicaInstanceInitParameters struct {

	// Specifies whether auto-renew is enabled. Valid values are true and false.
	AutoRenew *string `json:"autoRenew,omitempty" tf:"auto_renew,omitempty"`

	// Specifies the AZ name. Changing this parameter will create a new
	// resource.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Specifies the charging mode of the read replica instance. Valid values
	// are prePaid and postPaid, defaults to postPaid. Changing this creates a new resource.
	ChargingMode *string `json:"chargingMode,omitempty" tf:"charging_mode,omitempty"`

	// Specifies the database information. The db structure is documented below.
	// Changing this parameter will create a new resource.
	DB []ReadReplicaInstanceDBInitParameters `json:"db,omitempty" tf:"db,omitempty"`

	// Specifies the description of the instance. The value consists of 0 to 64
	// characters, including letters, digits, periods (.), underscores (_), and hyphens (-).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the enterprise project id of the read replica instance.
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	// Specifies an intranet floating IP address of read replica instance.
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	// Specifies the specification code.
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Specifies the time at which the maintenance time window starts, for example, 22:00.
	MaintainBegin *string `json:"maintainBegin,omitempty" tf:"maintain_begin,omitempty"`

	// Specifies the time at which the maintenance time window ends, for example, 01:00.
	MaintainEnd *string `json:"maintainEnd,omitempty" tf:"maintain_end,omitempty"`

	// Specifies the DB instance name. The DB instance name of the same type must be
	// unique for the same tenant. The value must be 4 to 64 characters in length and start with a letter. It is
	// case-sensitive and can contain only letters, digits, hyphens (-), and underscores (_). Changing this parameter will
	// create a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify an array of one or more parameters to be set to the read replica instance
	// after launched. You can check on console to see which parameters supported. The parameters
	// structure is documented below.
	Parameters []ReadReplicaInstanceParametersInitParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// Specifies the charging period of the read replica instance. If period_unit is
	// set to month, the value ranges from 1 to 9. If period_unit is set to year, the value ranges from 1 to 3.
	// This parameter is mandatory if charging_mode is set to prePaid. Changing this creates a new resource.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Specifies the charging period unit of the read replica instance. Valid
	// values are month and year. This parameter is mandatory if charging_mode is set to prePaid. Changing this
	// creates a new resource.
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// Specifies the DB instance ID, which is used to create a read
	// replica. Changing this parameter will create a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	PrimaryInstanceID *string `json:"primaryInstanceId,omitempty" tf:"primary_instance_id,omitempty"`

	// Reference to a Instance in rds to populate primaryInstanceId.
	// +kubebuilder:validation:Optional
	PrimaryInstanceIDRef *v1.Reference `json:"primaryInstanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate primaryInstanceId.
	// +kubebuilder:validation:Optional
	PrimaryInstanceIDSelector *v1.Selector `json:"primaryInstanceIdSelector,omitempty" tf:"-"`

	// The region in which to create the rds read replica instance resource. If
	// omitted, the provider-level region will be used.
	// Changing this parameter will create a new resource.
	// Currently, read replicas can be created only in the same region as that of the primary DB instance.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies whether to enable the SSL for read replica instance.
	SSLEnable *bool `json:"sslEnable,omitempty" tf:"ssl_enable,omitempty"`

	// Specifies the security group which the read replica instance belongs to.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/vpc/v1alpha1.Secgroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Reference to a Secgroup in vpc to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRef *v1.Reference `json:"securityGroupIdRef,omitempty" tf:"-"`

	// Selector for a Secgroup in vpc to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.Selector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// A mapping of tags to assign to the RDS read replica instance. Each tag is represented by one
	// key-value pair.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Specifies the volume information. The volume structure is
	// documented below. Changing this parameter will create a new resource.
	Volume []ReadReplicaInstanceVolumeInitParameters `json:"volume,omitempty" tf:"volume,omitempty"`
}

type ReadReplicaInstanceObservation struct {

	// Specifies whether auto-renew is enabled. Valid values are true and false.
	AutoRenew *string `json:"autoRenew,omitempty" tf:"auto_renew,omitempty"`

	// Specifies the AZ name. Changing this parameter will create a new
	// resource.
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Specifies the charging mode of the read replica instance. Valid values
	// are prePaid and postPaid, defaults to postPaid. Changing this creates a new resource.
	ChargingMode *string `json:"chargingMode,omitempty" tf:"charging_mode,omitempty"`

	// Specifies the database information. The db structure is documented below.
	// Changing this parameter will create a new resource.
	DB []ReadReplicaInstanceDBObservation `json:"db,omitempty" tf:"db,omitempty"`

	// Specifies the description of the instance. The value consists of 0 to 64
	// characters, including letters, digits, periods (.), underscores (_), and hyphens (-).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the enterprise project id of the read replica instance.
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	// Specifies an intranet floating IP address of read replica instance.
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	// Specifies the specification code.
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Indicates the instance ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the time at which the maintenance time window starts, for example, 22:00.
	MaintainBegin *string `json:"maintainBegin,omitempty" tf:"maintain_begin,omitempty"`

	// Specifies the time at which the maintenance time window ends, for example, 01:00.
	MaintainEnd *string `json:"maintainEnd,omitempty" tf:"maintain_end,omitempty"`

	// Specifies the DB instance name. The DB instance name of the same type must be
	// unique for the same tenant. The value must be 4 to 64 characters in length and start with a letter. It is
	// case-sensitive and can contain only letters, digits, hyphens (-), and underscores (_). Changing this parameter will
	// create a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify an array of one or more parameters to be set to the read replica instance
	// after launched. You can check on console to see which parameters supported. The parameters
	// structure is documented below.
	Parameters []ReadReplicaInstanceParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// Specifies the charging period of the read replica instance. If period_unit is
	// set to month, the value ranges from 1 to 9. If period_unit is set to year, the value ranges from 1 to 3.
	// This parameter is mandatory if charging_mode is set to prePaid. Changing this creates a new resource.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Specifies the charging period unit of the read replica instance. Valid
	// values are month and year. This parameter is mandatory if charging_mode is set to prePaid. Changing this
	// creates a new resource.
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// Specifies the DB instance ID, which is used to create a read
	// replica. Changing this parameter will create a new resource.
	PrimaryInstanceID *string `json:"primaryInstanceId,omitempty" tf:"primary_instance_id,omitempty"`

	// Indicates the private IP address list.
	PrivateIps []*string `json:"privateIps,omitempty" tf:"private_ips,omitempty"`

	// Indicates the public IP address list.
	PublicIps []*string `json:"publicIps,omitempty" tf:"public_ips,omitempty"`

	// The region in which to create the rds read replica instance resource. If
	// omitted, the provider-level region will be used.
	// Changing this parameter will create a new resource.
	// Currently, read replicas can be created only in the same region as that of the primary DB instance.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies whether to enable the SSL for read replica instance.
	SSLEnable *bool `json:"sslEnable,omitempty" tf:"ssl_enable,omitempty"`

	// Specifies the security group which the read replica instance belongs to.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Indicates the instance status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Indicates the subnet id.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// A mapping of tags to assign to the RDS read replica instance. Each tag is represented by one
	// key-value pair.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Indicates the type of the read replica instance. The value can be Single, Ha, Replica,
	// Enterprise.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Indicates the VPC ID.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Specifies the volume information. The volume structure is
	// documented below. Changing this parameter will create a new resource.
	Volume []ReadReplicaInstanceVolumeObservation `json:"volume,omitempty" tf:"volume,omitempty"`
}

type ReadReplicaInstanceParameters struct {

	// Specifies whether auto-renew is enabled. Valid values are true and false.
	// +kubebuilder:validation:Optional
	AutoRenew *string `json:"autoRenew,omitempty" tf:"auto_renew,omitempty"`

	// Specifies the AZ name. Changing this parameter will create a new
	// resource.
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Specifies the charging mode of the read replica instance. Valid values
	// are prePaid and postPaid, defaults to postPaid. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	ChargingMode *string `json:"chargingMode,omitempty" tf:"charging_mode,omitempty"`

	// Specifies the database information. The db structure is documented below.
	// Changing this parameter will create a new resource.
	// +kubebuilder:validation:Optional
	DB []ReadReplicaInstanceDBParameters `json:"db,omitempty" tf:"db,omitempty"`

	// Specifies the description of the instance. The value consists of 0 to 64
	// characters, including letters, digits, periods (.), underscores (_), and hyphens (-).
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the enterprise project id of the read replica instance.
	// +kubebuilder:validation:Optional
	EnterpriseProjectID *string `json:"enterpriseProjectId,omitempty" tf:"enterprise_project_id,omitempty"`

	// Specifies an intranet floating IP address of read replica instance.
	// +kubebuilder:validation:Optional
	FixedIP *string `json:"fixedIp,omitempty" tf:"fixed_ip,omitempty"`

	// Specifies the specification code.
	// +kubebuilder:validation:Optional
	Flavor *string `json:"flavor,omitempty" tf:"flavor,omitempty"`

	// Specifies the time at which the maintenance time window starts, for example, 22:00.
	// +kubebuilder:validation:Optional
	MaintainBegin *string `json:"maintainBegin,omitempty" tf:"maintain_begin,omitempty"`

	// Specifies the time at which the maintenance time window ends, for example, 01:00.
	// +kubebuilder:validation:Optional
	MaintainEnd *string `json:"maintainEnd,omitempty" tf:"maintain_end,omitempty"`

	// Specifies the DB instance name. The DB instance name of the same type must be
	// unique for the same tenant. The value must be 4 to 64 characters in length and start with a letter. It is
	// case-sensitive and can contain only letters, digits, hyphens (-), and underscores (_). Changing this parameter will
	// create a new resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify an array of one or more parameters to be set to the read replica instance
	// after launched. You can check on console to see which parameters supported. The parameters
	// structure is documented below.
	// +kubebuilder:validation:Optional
	Parameters []ReadReplicaInstanceParametersParameters `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// Specifies the charging period of the read replica instance. If period_unit is
	// set to month, the value ranges from 1 to 9. If period_unit is set to year, the value ranges from 1 to 3.
	// This parameter is mandatory if charging_mode is set to prePaid. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// Specifies the charging period unit of the read replica instance. Valid
	// values are month and year. This parameter is mandatory if charging_mode is set to prePaid. Changing this
	// creates a new resource.
	// +kubebuilder:validation:Optional
	PeriodUnit *string `json:"periodUnit,omitempty" tf:"period_unit,omitempty"`

	// Specifies the DB instance ID, which is used to create a read
	// replica. Changing this parameter will create a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/rds/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	PrimaryInstanceID *string `json:"primaryInstanceId,omitempty" tf:"primary_instance_id,omitempty"`

	// Reference to a Instance in rds to populate primaryInstanceId.
	// +kubebuilder:validation:Optional
	PrimaryInstanceIDRef *v1.Reference `json:"primaryInstanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in rds to populate primaryInstanceId.
	// +kubebuilder:validation:Optional
	PrimaryInstanceIDSelector *v1.Selector `json:"primaryInstanceIdSelector,omitempty" tf:"-"`

	// The region in which to create the rds read replica instance resource. If
	// omitted, the provider-level region will be used.
	// Changing this parameter will create a new resource.
	// Currently, read replicas can be created only in the same region as that of the primary DB instance.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies whether to enable the SSL for read replica instance.
	// +kubebuilder:validation:Optional
	SSLEnable *bool `json:"sslEnable,omitempty" tf:"ssl_enable,omitempty"`

	// Specifies the security group which the read replica instance belongs to.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/vpc/v1alpha1.Secgroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Reference to a Secgroup in vpc to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRef *v1.Reference `json:"securityGroupIdRef,omitempty" tf:"-"`

	// Selector for a Secgroup in vpc to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.Selector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// A mapping of tags to assign to the RDS read replica instance. Each tag is represented by one
	// key-value pair.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Specifies the volume information. The volume structure is
	// documented below. Changing this parameter will create a new resource.
	// +kubebuilder:validation:Optional
	Volume []ReadReplicaInstanceVolumeParameters `json:"volume,omitempty" tf:"volume,omitempty"`
}

type ReadReplicaInstanceParametersInitParameters struct {

	// Specifies the parameter name. Some of them needs the instance to be restarted
	// to take effect.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the parameter value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ReadReplicaInstanceParametersObservation struct {

	// Specifies the parameter name. Some of them needs the instance to be restarted
	// to take effect.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the parameter value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ReadReplicaInstanceParametersParameters struct {

	// Specifies the parameter name. Some of them needs the instance to be restarted
	// to take effect.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Specifies the parameter value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ReadReplicaInstanceVolumeInitParameters struct {

	// Indicates the instance ID.
	// schema: Computed
	DiskEncryptionID *string `json:"diskEncryptionId,omitempty" tf:"disk_encryption_id,omitempty"`

	// Specifies the upper limit of automatic expansion of storage, in GB.
	LimitSize *float64 `json:"limitSize,omitempty" tf:"limit_size,omitempty"`

	// Specifies the volume size. Its value range is from 40 GB to 4,000 GB. The value must
	// be a multiple of 10 and greater than the original size.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Specifies the threshold to trigger automatic expansion.
	// If the available storage drops to this threshold or 10 GB, the automatic expansion is triggered.
	// The valid values are as follows:
	TriggerThreshold *float64 `json:"triggerThreshold,omitempty" tf:"trigger_threshold,omitempty"`

	// Specifies the volume type. It must same with the type of the primary instance.
	// Its value can be any of the following and is case-sensitive:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReadReplicaInstanceVolumeObservation struct {

	// Indicates the instance ID.
	// schema: Computed
	DiskEncryptionID *string `json:"diskEncryptionId,omitempty" tf:"disk_encryption_id,omitempty"`

	// Specifies the upper limit of automatic expansion of storage, in GB.
	LimitSize *float64 `json:"limitSize,omitempty" tf:"limit_size,omitempty"`

	// Specifies the volume size. Its value range is from 40 GB to 4,000 GB. The value must
	// be a multiple of 10 and greater than the original size.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Specifies the threshold to trigger automatic expansion.
	// If the available storage drops to this threshold or 10 GB, the automatic expansion is triggered.
	// The valid values are as follows:
	TriggerThreshold *float64 `json:"triggerThreshold,omitempty" tf:"trigger_threshold,omitempty"`

	// Specifies the volume type. It must same with the type of the primary instance.
	// Its value can be any of the following and is case-sensitive:
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReadReplicaInstanceVolumeParameters struct {

	// Indicates the instance ID.
	// schema: Computed
	// +kubebuilder:validation:Optional
	DiskEncryptionID *string `json:"diskEncryptionId,omitempty" tf:"disk_encryption_id,omitempty"`

	// Specifies the upper limit of automatic expansion of storage, in GB.
	// +kubebuilder:validation:Optional
	LimitSize *float64 `json:"limitSize,omitempty" tf:"limit_size,omitempty"`

	// Specifies the volume size. Its value range is from 40 GB to 4,000 GB. The value must
	// be a multiple of 10 and greater than the original size.
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Specifies the threshold to trigger automatic expansion.
	// If the available storage drops to this threshold or 10 GB, the automatic expansion is triggered.
	// The valid values are as follows:
	// +kubebuilder:validation:Optional
	TriggerThreshold *float64 `json:"triggerThreshold,omitempty" tf:"trigger_threshold,omitempty"`

	// Specifies the volume type. It must same with the type of the primary instance.
	// Its value can be any of the following and is case-sensitive:
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// ReadReplicaInstanceSpec defines the desired state of ReadReplicaInstance
type ReadReplicaInstanceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ReadReplicaInstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReadReplicaInstanceInitParameters `json:"initProvider,omitempty"`
}

// ReadReplicaInstanceStatus defines the observed state of ReadReplicaInstance.
type ReadReplicaInstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReadReplicaInstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReadReplicaInstance is the Schema for the ReadReplicaInstances API. ""
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type ReadReplicaInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.availabilityZone) || (has(self.initProvider) && has(self.initProvider.availabilityZone))",message="spec.forProvider.availabilityZone is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.flavor) || (has(self.initProvider) && has(self.initProvider.flavor))",message="spec.forProvider.flavor is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.volume) || (has(self.initProvider) && has(self.initProvider.volume))",message="spec.forProvider.volume is a required parameter"
	Spec   ReadReplicaInstanceSpec   `json:"spec"`
	Status ReadReplicaInstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReadReplicaInstanceList contains a list of ReadReplicaInstances
type ReadReplicaInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReadReplicaInstance `json:"items"`
}

// Repository type metadata.
var (
	ReadReplicaInstance_Kind             = "ReadReplicaInstance"
	ReadReplicaInstance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReadReplicaInstance_Kind}.String()
	ReadReplicaInstance_KindAPIVersion   = ReadReplicaInstance_Kind + "." + CRDGroupVersion.String()
	ReadReplicaInstance_GroupVersionKind = CRDGroupVersion.WithKind(ReadReplicaInstance_Kind)
)

func init() {
	SchemeBuilder.Register(&ReadReplicaInstance{}, &ReadReplicaInstanceList{})
}
