apiVersion: obs.huaweicloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketacl
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accountPermission:
    - accessToAcl:
      - READ_ACP
      - WRITE_ACP
      accessToBucket:
      - READ
      - WRITE
      accountId: your_account_id
    - accessToAcl:
      - READ_ACP
      - WRITE_ACP
      accessToBucket:
      - READ
      accountId: your_account_id
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    logDeliveryUserPermission:
    - accessToAcl:
      - READ_ACP
      - WRITE_ACP
      accessToBucket:
      - READ
      - WRITE
    ownerPermission:
    - accessToAcl:
      - READ_ACP
      - WRITE_ACP
      accessToBucket:
      - READ
      - WRITE
    publicPermission:
    - accessToBucket:
      - READ
      - WRITE

apiVersion: obs.huaweicloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    acl: private
    bucket: my-tf-test-bucket
    tags:
      Env: Test
      foo: bar
