apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: VpcBandwidthAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/vpcbandwidthassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bandwidthIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    eipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: VpcBandwidth
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/vpcbandwidthassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: bandwidth_1
    size: 100
