// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *RabbitmqExchange) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqExchangeAssociate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqPlugin) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqQueue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqQueueMessageClear) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RabbitmqVhost) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RocketmqConsumerGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RocketmqInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RocketmqMigrationTask) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RocketmqTopic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RocketmqUser) Hub() {}
