apiVersion: modelarts.huaweicloud.crossplane.io/v1alpha1
kind: ResourcePool
metadata:
  annotations:
    meta.upbound.io/example-id: modelarts/v1alpha1/resourcepool
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    clusters:
    - providerId: ${var.cce_cluster_id}
    description: This is a demo
    name: demo
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resources:
    - count: 1
      dataVolumes:
      - extendParams: |-
          ${jsonencode({
                  "billing": "on",
                  "volumeGroup": "vguser0"
                })}
        size: 500Gi
        volumeType: SSD
      extendParams: |-
        ${jsonencode({
              "dockerBaseSize": "50",
              "runtime": "docker"
            })}
      flavorId: modelarts.vm.cpu.16u64g.d
      volumeGroupConfigs:
      - lvmConfig:
        - lvType: linear
        types:
        - local
        volumeGroup: vgpaas
      - lvmConfig:
        - lvType: linear
          path: /data
        volumeGroup: vguser0
    scope:
    - Train
    - Infer
    - Notebook
    userLogin:
    - keyPairName: ${var.login_key_pair_name}
