apiVersion: modelarts.huaweicloud.crossplane.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: modelarts/v1alpha1/workspace
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: This is a demo
    name: demo
