// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConfigsInitParameters struct {

	// Specifies the configuration name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the configuration value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ConfigsObservation struct {

	// Specifies the configuration name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the configuration value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ConfigsParameters struct {

	// Specifies the configuration name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Specifies the configuration value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type KafkaTopicInitParameters struct {

	// Specifies the aging time in hours.
	// The value ranges from 1 to 720 and defaults to 72.
	AgingTime *float64 `json:"agingTime,omitempty" tf:"aging_time,omitempty"`

	// Specifies the other topic configurations.
	Configs []ConfigsInitParameters `json:"configs,omitempty" tf:"configs,omitempty"`

	// Specifies the description of topic.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the ID of the DMS kafka instance to which the topic belongs.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies the name of the topic. The name starts with a letter, consists of 3 to
	// 200 characters, and supports only letters, digits, hyphens (-), underscores (_) and periods (.).
	// Changing this creates a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the integers list of brokers for new partitions.
	// +listType=set
	NewPartitionBrokers []*float64 `json:"newPartitionBrokers,omitempty" tf:"new_partition_brokers,omitempty"`

	// Specifies the partition number. The value ranges from 1 to 200.
	Partitions *float64 `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// The region in which to create the DMS kafka topic resource. If omitted, the
	// provider-level region will be used. Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the replica number.
	// The value ranges from 1 to 3 and defaults to 3. Changing this creates a new resource.
	Replicas *float64 `json:"replicas,omitempty" tf:"replicas,omitempty"`

	// Whether or not to enable synchronous flushing.
	SyncFlushing *bool `json:"syncFlushing,omitempty" tf:"sync_flushing,omitempty"`

	// Whether or not to enable synchronous replication.
	SyncReplication *bool `json:"syncReplication,omitempty" tf:"sync_replication,omitempty"`
}

type KafkaTopicObservation struct {

	// Specifies the aging time in hours.
	// The value ranges from 1 to 720 and defaults to 72.
	AgingTime *float64 `json:"agingTime,omitempty" tf:"aging_time,omitempty"`

	// Specifies the other topic configurations.
	Configs []ConfigsObservation `json:"configs,omitempty" tf:"configs,omitempty"`

	// Indicates the topic create time.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Specifies the description of topic.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The resource ID which equals to the topic name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the ID of the DMS kafka instance to which the topic belongs.
	// Changing this creates a new resource.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Specifies the name of the topic. The name starts with a letter, consists of 3 to
	// 200 characters, and supports only letters, digits, hyphens (-), underscores (_) and periods (.).
	// Changing this creates a new resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the integers list of brokers for new partitions.
	// +listType=set
	NewPartitionBrokers []*float64 `json:"newPartitionBrokers,omitempty" tf:"new_partition_brokers,omitempty"`

	// Specifies the partition number. The value ranges from 1 to 200.
	Partitions *float64 `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// Indicates whether this policy is the default policy.
	PoliciesOnly *bool `json:"policiesOnly,omitempty" tf:"policies_only,omitempty"`

	// The region in which to create the DMS kafka topic resource. If omitted, the
	// provider-level region will be used. Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the replica number.
	// The value ranges from 1 to 3 and defaults to 3. Changing this creates a new resource.
	Replicas *float64 `json:"replicas,omitempty" tf:"replicas,omitempty"`

	// Whether or not to enable synchronous flushing.
	SyncFlushing *bool `json:"syncFlushing,omitempty" tf:"sync_flushing,omitempty"`

	// Whether or not to enable synchronous replication.
	SyncReplication *bool `json:"syncReplication,omitempty" tf:"sync_replication,omitempty"`

	// Indicates the topic type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type KafkaTopicParameters struct {

	// Specifies the aging time in hours.
	// The value ranges from 1 to 720 and defaults to 72.
	// +kubebuilder:validation:Optional
	AgingTime *float64 `json:"agingTime,omitempty" tf:"aging_time,omitempty"`

	// Specifies the other topic configurations.
	// +kubebuilder:validation:Optional
	Configs []ConfigsParameters `json:"configs,omitempty" tf:"configs,omitempty"`

	// Specifies the description of topic.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Specifies the ID of the DMS kafka instance to which the topic belongs.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies the name of the topic. The name starts with a letter, consists of 3 to
	// 200 characters, and supports only letters, digits, hyphens (-), underscores (_) and periods (.).
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies the integers list of brokers for new partitions.
	// +kubebuilder:validation:Optional
	// +listType=set
	NewPartitionBrokers []*float64 `json:"newPartitionBrokers,omitempty" tf:"new_partition_brokers,omitempty"`

	// Specifies the partition number. The value ranges from 1 to 200.
	// +kubebuilder:validation:Optional
	Partitions *float64 `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// The region in which to create the DMS kafka topic resource. If omitted, the
	// provider-level region will be used. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the replica number.
	// The value ranges from 1 to 3 and defaults to 3. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Replicas *float64 `json:"replicas,omitempty" tf:"replicas,omitempty"`

	// Whether or not to enable synchronous flushing.
	// +kubebuilder:validation:Optional
	SyncFlushing *bool `json:"syncFlushing,omitempty" tf:"sync_flushing,omitempty"`

	// Whether or not to enable synchronous replication.
	// +kubebuilder:validation:Optional
	SyncReplication *bool `json:"syncReplication,omitempty" tf:"sync_replication,omitempty"`
}

// KafkaTopicSpec defines the desired state of KafkaTopic
type KafkaTopicSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KafkaTopicParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KafkaTopicInitParameters `json:"initProvider,omitempty"`
}

// KafkaTopicStatus defines the observed state of KafkaTopic.
type KafkaTopicStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KafkaTopicObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KafkaTopic is the Schema for the KafkaTopics API. ""
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type KafkaTopic struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.partitions) || (has(self.initProvider) && has(self.initProvider.partitions))",message="spec.forProvider.partitions is a required parameter"
	Spec   KafkaTopicSpec   `json:"spec"`
	Status KafkaTopicStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KafkaTopicList contains a list of KafkaTopics
type KafkaTopicList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KafkaTopic `json:"items"`
}

// Repository type metadata.
var (
	KafkaTopic_Kind             = "KafkaTopic"
	KafkaTopic_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KafkaTopic_Kind}.String()
	KafkaTopic_KindAPIVersion   = KafkaTopic_Kind + "." + CRDGroupVersion.String()
	KafkaTopic_GroupVersionKind = CRDGroupVersion.WithKind(KafkaTopic_Kind)
)

func init() {
	SchemeBuilder.Register(&KafkaTopic{}, &KafkaTopicList{})
}
