// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AssignmentInitParameters struct {

	// Specifies the partition number in manual assignment.
	// It's actually required in manual assignment plan. Changing this creates a new resource.
	Partition *float64 `json:"partition,omitempty" tf:"partition,omitempty"`

	// Specifies the integer list of brokers to be assigned to a partition in
	// manual assignment. It's actually required in manual assignment plan. Changing this creates a new resource.
	PartitionBrokers []*float64 `json:"partitionBrokers,omitempty" tf:"partition_brokers,omitempty"`
}

type AssignmentObservation struct {

	// Specifies the partition number in manual assignment.
	// It's actually required in manual assignment plan. Changing this creates a new resource.
	Partition *float64 `json:"partition,omitempty" tf:"partition,omitempty"`

	// Specifies the integer list of brokers to be assigned to a partition in
	// manual assignment. It's actually required in manual assignment plan. Changing this creates a new resource.
	PartitionBrokers []*float64 `json:"partitionBrokers,omitempty" tf:"partition_brokers,omitempty"`
}

type AssignmentParameters struct {

	// Specifies the partition number in manual assignment.
	// It's actually required in manual assignment plan. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Partition *float64 `json:"partition,omitempty" tf:"partition,omitempty"`

	// Specifies the integer list of brokers to be assigned to a partition in
	// manual assignment. It's actually required in manual assignment plan. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	PartitionBrokers []*float64 `json:"partitionBrokers,omitempty" tf:"partition_brokers,omitempty"`
}

type KafkaPartitionReassignInitParameters struct {

	// Specifies the schedule time. The value is a UNIX timestamp, in ms.
	// It's required if is_schedule is true. Changing this creates a new resource.
	ExecuteAt *float64 `json:"executeAt,omitempty" tf:"execute_at,omitempty"`

	// Specifies the DMS kafka instance ID.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies whether the task is scheduled. Defaults to false.
	// Changing this creates a new resource.
	IsSchedule *bool `json:"isSchedule,omitempty" tf:"is_schedule,omitempty"`

	// Specifies the reassignment plan.
	// Changing this creates a new resource.
	// The reassignments structure is documented below.
	Reassignments []ReassignmentsInitParameters `json:"reassignments,omitempty" tf:"reassignments,omitempty"`

	// The region in which to create the resource.
	// If omitted, the provider-level region will be used. Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the reassignment threshold. Value can be specified ranges from 1
	// to 300. The unit is MB/s. Or specifies it to -1, indicating no throttling required.
	// Changing this creates a new resource.
	Throttle *float64 `json:"throttle,omitempty" tf:"throttle,omitempty"`

	// Specifies whether to perform time estimation tasks. Defaults to false.
	// Changing this creates a new resource.
	TimeEstimate *bool `json:"timeEstimate,omitempty" tf:"time_estimate,omitempty"`
}

type KafkaPartitionReassignObservation struct {

	// Specifies the schedule time. The value is a UNIX timestamp, in ms.
	// It's required if is_schedule is true. Changing this creates a new resource.
	ExecuteAt *float64 `json:"executeAt,omitempty" tf:"execute_at,omitempty"`

	// The resource ID in UUID format.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the DMS kafka instance ID.
	// Changing this creates a new resource.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Specifies whether the task is scheduled. Defaults to false.
	// Changing this creates a new resource.
	IsSchedule *bool `json:"isSchedule,omitempty" tf:"is_schedule,omitempty"`

	// Indicates the estimated time, in seconds, and it's only returned for a time estimation task.
	ReassignmentTime *float64 `json:"reassignmentTime,omitempty" tf:"reassignment_time,omitempty"`

	// Specifies the reassignment plan.
	// Changing this creates a new resource.
	// The reassignments structure is documented below.
	Reassignments []ReassignmentsObservation `json:"reassignments,omitempty" tf:"reassignments,omitempty"`

	// The region in which to create the resource.
	// If omitted, the provider-level region will be used. Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Indicates the task ID, and it's only returned for a partition reassignment task.
	TaskID *string `json:"taskId,omitempty" tf:"task_id,omitempty"`

	// Specifies the reassignment threshold. Value can be specified ranges from 1
	// to 300. The unit is MB/s. Or specifies it to -1, indicating no throttling required.
	// Changing this creates a new resource.
	Throttle *float64 `json:"throttle,omitempty" tf:"throttle,omitempty"`

	// Specifies whether to perform time estimation tasks. Defaults to false.
	// Changing this creates a new resource.
	TimeEstimate *bool `json:"timeEstimate,omitempty" tf:"time_estimate,omitempty"`
}

type KafkaPartitionReassignParameters struct {

	// Specifies the schedule time. The value is a UNIX timestamp, in ms.
	// It's required if is_schedule is true. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	ExecuteAt *float64 `json:"executeAt,omitempty" tf:"execute_at,omitempty"`

	// Specifies the DMS kafka instance ID.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies whether the task is scheduled. Defaults to false.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	IsSchedule *bool `json:"isSchedule,omitempty" tf:"is_schedule,omitempty"`

	// Specifies the reassignment plan.
	// Changing this creates a new resource.
	// The reassignments structure is documented below.
	// +kubebuilder:validation:Optional
	Reassignments []ReassignmentsParameters `json:"reassignments,omitempty" tf:"reassignments,omitempty"`

	// The region in which to create the resource.
	// If omitted, the provider-level region will be used. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the reassignment threshold. Value can be specified ranges from 1
	// to 300. The unit is MB/s. Or specifies it to -1, indicating no throttling required.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Throttle *float64 `json:"throttle,omitempty" tf:"throttle,omitempty"`

	// Specifies whether to perform time estimation tasks. Defaults to false.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	TimeEstimate *bool `json:"timeEstimate,omitempty" tf:"time_estimate,omitempty"`
}

type ReassignmentsInitParameters struct {

	// Specifies the manually specified assignment plan.
	// It's required in manually specified assignment. Changing this creates a new resource.
	// The assignment structure is documented below.
	Assignment []AssignmentInitParameters `json:"assignment,omitempty" tf:"assignment,omitempty"`

	// Specifies the integer list of brokers to which partitions are reassigned.
	// It's required in automatic assignment. Changing this creates a new resource.
	Brokers []*float64 `json:"brokers,omitempty" tf:"brokers,omitempty"`

	// Specifies the replication factor, which can be specified in
	// automatic assignment. Changing this creates a new resource.
	ReplicationFactor *float64 `json:"replicationFactor,omitempty" tf:"replication_factor,omitempty"`

	// Specifies the topic name. Changing this creates a new resource.
	Topic *string `json:"topic,omitempty" tf:"topic,omitempty"`
}

type ReassignmentsObservation struct {

	// Specifies the manually specified assignment plan.
	// It's required in manually specified assignment. Changing this creates a new resource.
	// The assignment structure is documented below.
	Assignment []AssignmentObservation `json:"assignment,omitempty" tf:"assignment,omitempty"`

	// Specifies the integer list of brokers to which partitions are reassigned.
	// It's required in automatic assignment. Changing this creates a new resource.
	Brokers []*float64 `json:"brokers,omitempty" tf:"brokers,omitempty"`

	// Specifies the replication factor, which can be specified in
	// automatic assignment. Changing this creates a new resource.
	ReplicationFactor *float64 `json:"replicationFactor,omitempty" tf:"replication_factor,omitempty"`

	// Specifies the topic name. Changing this creates a new resource.
	Topic *string `json:"topic,omitempty" tf:"topic,omitempty"`
}

type ReassignmentsParameters struct {

	// Specifies the manually specified assignment plan.
	// It's required in manually specified assignment. Changing this creates a new resource.
	// The assignment structure is documented below.
	// +kubebuilder:validation:Optional
	Assignment []AssignmentParameters `json:"assignment,omitempty" tf:"assignment,omitempty"`

	// Specifies the integer list of brokers to which partitions are reassigned.
	// It's required in automatic assignment. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Brokers []*float64 `json:"brokers,omitempty" tf:"brokers,omitempty"`

	// Specifies the replication factor, which can be specified in
	// automatic assignment. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	ReplicationFactor *float64 `json:"replicationFactor,omitempty" tf:"replication_factor,omitempty"`

	// Specifies the topic name. Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Topic *string `json:"topic" tf:"topic,omitempty"`
}

// KafkaPartitionReassignSpec defines the desired state of KafkaPartitionReassign
type KafkaPartitionReassignSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KafkaPartitionReassignParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KafkaPartitionReassignInitParameters `json:"initProvider,omitempty"`
}

// KafkaPartitionReassignStatus defines the observed state of KafkaPartitionReassign.
type KafkaPartitionReassignStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KafkaPartitionReassignObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KafkaPartitionReassign is the Schema for the KafkaPartitionReassigns API. Manages a DMS kafka partition reassign resource within HuaweiCloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type KafkaPartitionReassign struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.reassignments) || (has(self.initProvider) && has(self.initProvider.reassignments))",message="spec.forProvider.reassignments is a required parameter"
	Spec   KafkaPartitionReassignSpec   `json:"spec"`
	Status KafkaPartitionReassignStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KafkaPartitionReassignList contains a list of KafkaPartitionReassigns
type KafkaPartitionReassignList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KafkaPartitionReassign `json:"items"`
}

// Repository type metadata.
var (
	KafkaPartitionReassign_Kind             = "KafkaPartitionReassign"
	KafkaPartitionReassign_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KafkaPartitionReassign_Kind}.String()
	KafkaPartitionReassign_KindAPIVersion   = KafkaPartitionReassign_Kind + "." + CRDGroupVersion.String()
	KafkaPartitionReassign_GroupVersionKind = CRDGroupVersion.WithKind(KafkaPartitionReassign_Kind)
)

func init() {
	SchemeBuilder.Register(&KafkaPartitionReassign{}, &KafkaPartitionReassignList{})
}
