// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AdviceIdsInitParameters struct {
}

type AdviceIdsObservation struct {

	// The resource ID.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// Indicates the diagnosis conclusion parameters.
	// +mapType=granular
	Params map[string]*string `json:"params,omitempty" tf:"params,omitempty"`
}

type AdviceIdsParameters struct {
}

type CauseIdsInitParameters struct {
}

type CauseIdsObservation struct {

	// The resource ID.
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// Indicates the diagnosis conclusion parameters.
	// +mapType=granular
	Params map[string]*string `json:"params,omitempty" tf:"params,omitempty"`
}

type CauseIdsParameters struct {
}

type DiagnosisDimensionListInitParameters struct {
}

type DiagnosisDimensionListObservation struct {

	// Indicates the total number of abnormal items in this diagnosis dimension.
	AbnormalNum *float64 `json:"abnormalNum,omitempty" tf:"abnormal_num,omitempty"`

	// Indicates the diagnosis items.
	// The diagnosis_item_list structure is documented below.
	DiagnosisItemList []DiagnosisItemListObservation `json:"diagnosisItemList,omitempty" tf:"diagnosis_item_list,omitempty"`

	// Indicates the total number of failed items in this diagnosis dimension.
	FailedNum *float64 `json:"failedNum,omitempty" tf:"failed_num,omitempty"`

	// Indicates the diagnosis dimension name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type DiagnosisDimensionListParameters struct {
}

type DiagnosisItemListInitParameters struct {
}

type DiagnosisItemListObservation struct {

	// Indicates the suggestions for diagnosis exceptions.
	// The conclusion structure is documented below.
	AdviceIds []AdviceIdsObservation `json:"adviceIds,omitempty" tf:"advice_ids,omitempty"`

	// Indicates the brokers affected by the diagnosis exceptions.
	BrokerIds []*float64 `json:"brokerIds,omitempty" tf:"broker_ids,omitempty"`

	// Indicates the diagnosis exception causes.
	// The conclusion structure is documented below.
	CauseIds []CauseIdsObservation `json:"causeIds,omitempty" tf:"cause_ids,omitempty"`

	// Indicates the partitions that failed to be diagnosed.
	FailedPartitions []*float64 `json:"failedPartitions,omitempty" tf:"failed_partitions,omitempty"`

	// Indicates the diagnosis item name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Indicates the partitions affected by the diagnosis exceptions.
	Partitions []*float64 `json:"partitions,omitempty" tf:"partitions,omitempty"`

	// Indicates the diagnosis result.
	Result *string `json:"result,omitempty" tf:"result,omitempty"`
}

type DiagnosisItemListParameters struct {
}

type KafkaMessageDiagnosisTaskInitParameters struct {

	// Specifies the group name.
	// Changing this creates a new resource.
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Specifies the kafka instance ID.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the topic name.
	// Changing this creates a new resource.
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

type KafkaMessageDiagnosisTaskObservation struct {

	// Indicates the number of partitions where accumulated messages are found.
	AccumulatedPartitions *float64 `json:"accumulatedPartitions,omitempty" tf:"accumulated_partitions,omitempty"`

	// Indicates the diagnosis task start time.
	BeginTime *string `json:"beginTime,omitempty" tf:"begin_time,omitempty"`

	// Indicates the diagnosis dimensions.
	// The diagnosis_dimension_list structure is documented below.
	DiagnosisDimensionList []DiagnosisDimensionListObservation `json:"diagnosisDimensionList,omitempty" tf:"diagnosis_dimension_list,omitempty"`

	// Indicates the diagnosis task end time.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// Specifies the group name.
	// Changing this creates a new resource.
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// The resource ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the kafka instance ID.
	// Changing this creates a new resource.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Indicates the status of a message stack diagnosis task.
	// Value can be as follows:
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Specifies the topic name.
	// Changing this creates a new resource.
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

type KafkaMessageDiagnosisTaskParameters struct {

	// Specifies the group name.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	GroupName *string `json:"groupName,omitempty" tf:"group_name,omitempty"`

	// Specifies the kafka instance ID.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the topic name.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	TopicName *string `json:"topicName,omitempty" tf:"topic_name,omitempty"`
}

// KafkaMessageDiagnosisTaskSpec defines the desired state of KafkaMessageDiagnosisTask
type KafkaMessageDiagnosisTaskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KafkaMessageDiagnosisTaskParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KafkaMessageDiagnosisTaskInitParameters `json:"initProvider,omitempty"`
}

// KafkaMessageDiagnosisTaskStatus defines the observed state of KafkaMessageDiagnosisTask.
type KafkaMessageDiagnosisTaskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KafkaMessageDiagnosisTaskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KafkaMessageDiagnosisTask is the Schema for the KafkaMessageDiagnosisTasks API. Manage DMS kafka message diagnosis task resource within HuaweiCloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type KafkaMessageDiagnosisTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.groupName) || (has(self.initProvider) && has(self.initProvider.groupName))",message="spec.forProvider.groupName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.topicName) || (has(self.initProvider) && has(self.initProvider.topicName))",message="spec.forProvider.topicName is a required parameter"
	Spec   KafkaMessageDiagnosisTaskSpec   `json:"spec"`
	Status KafkaMessageDiagnosisTaskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KafkaMessageDiagnosisTaskList contains a list of KafkaMessageDiagnosisTasks
type KafkaMessageDiagnosisTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KafkaMessageDiagnosisTask `json:"items"`
}

// Repository type metadata.
var (
	KafkaMessageDiagnosisTask_Kind             = "KafkaMessageDiagnosisTask"
	KafkaMessageDiagnosisTask_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KafkaMessageDiagnosisTask_Kind}.String()
	KafkaMessageDiagnosisTask_KindAPIVersion   = KafkaMessageDiagnosisTask_Kind + "." + CRDGroupVersion.String()
	KafkaMessageDiagnosisTask_GroupVersionKind = CRDGroupVersion.WithKind(KafkaMessageDiagnosisTask_Kind)
)

func init() {
	SchemeBuilder.Register(&KafkaMessageDiagnosisTask{}, &KafkaMessageDiagnosisTaskList{})
}
