// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type KafkaBackgroundTaskDeleteInitParameters struct {

	// Specifies the instance ID.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the task ID.
	// Changing this creates a new resource.
	TaskID *string `json:"taskId,omitempty" tf:"task_id,omitempty"`
}

type KafkaBackgroundTaskDeleteObservation struct {

	// The resource ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the instance ID.
	// Changing this creates a new resource.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// Changing this creates a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the task ID.
	// Changing this creates a new resource.
	TaskID *string `json:"taskId,omitempty" tf:"task_id,omitempty"`
}

type KafkaBackgroundTaskDeleteParameters struct {

	// Specifies the instance ID.
	// Changing this creates a new resource.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the task ID.
	// Changing this creates a new resource.
	// +kubebuilder:validation:Optional
	TaskID *string `json:"taskId,omitempty" tf:"task_id,omitempty"`
}

// KafkaBackgroundTaskDeleteSpec defines the desired state of KafkaBackgroundTaskDelete
type KafkaBackgroundTaskDeleteSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KafkaBackgroundTaskDeleteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KafkaBackgroundTaskDeleteInitParameters `json:"initProvider,omitempty"`
}

// KafkaBackgroundTaskDeleteStatus defines the observed state of KafkaBackgroundTaskDelete.
type KafkaBackgroundTaskDeleteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KafkaBackgroundTaskDeleteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KafkaBackgroundTaskDelete is the Schema for the KafkaBackgroundTaskDeletes API. Manages a DMS kafka background task delete resource within HuaweiCloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type KafkaBackgroundTaskDelete struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.taskId) || (has(self.initProvider) && has(self.initProvider.taskId))",message="spec.forProvider.taskId is a required parameter"
	Spec   KafkaBackgroundTaskDeleteSpec   `json:"spec"`
	Status KafkaBackgroundTaskDeleteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KafkaBackgroundTaskDeleteList contains a list of KafkaBackgroundTaskDeletes
type KafkaBackgroundTaskDeleteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KafkaBackgroundTaskDelete `json:"items"`
}

// Repository type metadata.
var (
	KafkaBackgroundTaskDelete_Kind             = "KafkaBackgroundTaskDelete"
	KafkaBackgroundTaskDelete_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KafkaBackgroundTaskDelete_Kind}.String()
	KafkaBackgroundTaskDelete_KindAPIVersion   = KafkaBackgroundTaskDelete_Kind + "." + CRDGroupVersion.String()
	KafkaBackgroundTaskDelete_GroupVersionKind = CRDGroupVersion.WithKind(KafkaBackgroundTaskDelete_Kind)
)

func init() {
	SchemeBuilder.Register(&KafkaBackgroundTaskDelete{}, &KafkaBackgroundTaskDeleteList{})
}
