// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type KafkaSmartConnectTaskInitParameters struct {

	// Specifies the access key used to access the OBS bucket.
	// Changing this parameter will create a new resource.
	// Specifies the access key used to access the OBS bucket.
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// Specifies the connector ID of the kafka instance.
	// Changing this parameter will create a new resource.
	// Specifies the connector id of the kafka instance.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("connector_id",true)
	ConnectorID *string `json:"connectorId,omitempty" tf:"connector_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate connectorId.
	// +kubebuilder:validation:Optional
	ConnectorIDRef *v1.Reference `json:"connectorIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate connectorId.
	// +kubebuilder:validation:Optional
	ConnectorIDSelector *v1.Selector `json:"connectorIdSelector,omitempty" tf:"-"`

	// Specifies the consumer strategy of the smart connect task.
	// Changing this parameter will create a new resource.
	// Value options:
	// Specifies the consumer strategy of the smart connect task.
	ConsumerStrategy *string `json:"consumerStrategy,omitempty" tf:"consumer_strategy,omitempty"`

	// Specifies the deliver time interval of the smart connect task.
	// The value should be between 30 and 900. Changing this parameter will create a new resource.
	// Specifies the deliver time interval of the smart connect task.
	DeliverTimeInterval *float64 `json:"deliverTimeInterval,omitempty" tf:"deliver_time_interval,omitempty"`

	// Specifies the destination file type of the smart connect task.
	// Only TEXT is supported. Changing this parameter will create a new resource.
	// Specifies the destination file type of the smart connect task.
	DestinationFileType *string `json:"destinationFileType,omitempty" tf:"destination_file_type,omitempty"`

	// Specifies the destination type of the smart connect task.
	// Only OBS is supported. Changing this parameter will create a new resource.
	// Specifies the destination type of the smart connect task.
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// Specifies the obs bucket name of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the obs bucket name of the smart connect task.
	ObsBucketName *string `json:"obsBucketName,omitempty" tf:"obs_bucket_name,omitempty"`

	// Specifies the obs path of the smart connect task.
	// Obs path is separated by a slash. Changing this parameter will create a new resource.
	// Specifies the obs path of the smart connect task.
	ObsPath *string `json:"obsPath,omitempty" tf:"obs_path,omitempty"`

	// Specifies the time directory format of the smart connect task.
	// Value options: yyyy, yyyy/MM, yyyy/MM/dd, yyyy/MM/dd/HH, yyyy/MM/dd/HH/mm.
	// Changing this parameter will create a new resource.
	// Specifies the partiton format of the smart connect task.
	PartitionFormat *string `json:"partitionFormat,omitempty" tf:"partition_format,omitempty"`

	// Specifies the record delimiter of the smart connect task.
	// Value options: ,, ;, |, \n, "". Defaults to \n.
	// Changing this parameter will create a new resource.
	// Specifies the record delimiter of the smart connect task.
	RecordDelimiter *string `json:"recordDelimiter,omitempty" tf:"record_delimiter,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the secret access key used to access the OBS bucket.
	// Changing this parameter will create a new resource.
	// Specifies the secret access key used to access the OBS bucket.
	SecretKeySecretRef v1.SecretKeySelector `json:"secretKeySecretRef" tf:"-"`

	// Specifies the source type of the smart connect task.
	// Only BLOB is supported. Changing this parameter will create a new resource.
	// Specifies the source type of the smart connect task.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// Specifies the name of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the name of the smart connect task.
	TaskName *string `json:"taskName,omitempty" tf:"task_name,omitempty"`

	// Specifies the topic names separated by a comma of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the topics of the task.
	Topics *string `json:"topics,omitempty" tf:"topics,omitempty"`

	// Specifies the regular expression of topic name for the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the topics regular expression of the smart connect task.
	TopicsRegex *string `json:"topicsRegex,omitempty" tf:"topics_regex,omitempty"`
}

type KafkaSmartConnectTaskObservation struct {

	// Specifies the access key used to access the OBS bucket.
	// Changing this parameter will create a new resource.
	// Specifies the access key used to access the OBS bucket.
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// Specifies the connector ID of the kafka instance.
	// Changing this parameter will create a new resource.
	// Specifies the connector id of the kafka instance.
	ConnectorID *string `json:"connectorId,omitempty" tf:"connector_id,omitempty"`

	// Specifies the consumer strategy of the smart connect task.
	// Changing this parameter will create a new resource.
	// Value options:
	// Specifies the consumer strategy of the smart connect task.
	ConsumerStrategy *string `json:"consumerStrategy,omitempty" tf:"consumer_strategy,omitempty"`

	// Indicates the creation time of the smart connect task.
	// Indicates the creation time of the smart connect task.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Specifies the deliver time interval of the smart connect task.
	// The value should be between 30 and 900. Changing this parameter will create a new resource.
	// Specifies the deliver time interval of the smart connect task.
	DeliverTimeInterval *float64 `json:"deliverTimeInterval,omitempty" tf:"deliver_time_interval,omitempty"`

	// Specifies the destination file type of the smart connect task.
	// Only TEXT is supported. Changing this parameter will create a new resource.
	// Specifies the destination file type of the smart connect task.
	DestinationFileType *string `json:"destinationFileType,omitempty" tf:"destination_file_type,omitempty"`

	// Specifies the destination type of the smart connect task.
	// Only OBS is supported. Changing this parameter will create a new resource.
	// Specifies the destination type of the smart connect task.
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// The resource ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the obs bucket name of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the obs bucket name of the smart connect task.
	ObsBucketName *string `json:"obsBucketName,omitempty" tf:"obs_bucket_name,omitempty"`

	// Specifies the obs path of the smart connect task.
	// Obs path is separated by a slash. Changing this parameter will create a new resource.
	// Specifies the obs path of the smart connect task.
	ObsPath *string `json:"obsPath,omitempty" tf:"obs_path,omitempty"`

	// Specifies the time directory format of the smart connect task.
	// Value options: yyyy, yyyy/MM, yyyy/MM/dd, yyyy/MM/dd/HH, yyyy/MM/dd/HH/mm.
	// Changing this parameter will create a new resource.
	// Specifies the partiton format of the smart connect task.
	PartitionFormat *string `json:"partitionFormat,omitempty" tf:"partition_format,omitempty"`

	// Specifies the record delimiter of the smart connect task.
	// Value options: ,, ;, |, \n, "". Defaults to \n.
	// Changing this parameter will create a new resource.
	// Specifies the record delimiter of the smart connect task.
	RecordDelimiter *string `json:"recordDelimiter,omitempty" tf:"record_delimiter,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the source type of the smart connect task.
	// Only BLOB is supported. Changing this parameter will create a new resource.
	// Specifies the source type of the smart connect task.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// Indicates the status of the smart connect task. The value can be RUNNING, PAUSED.
	// Indicates the status of the smart connect task.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Specifies the name of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the name of the smart connect task.
	TaskName *string `json:"taskName,omitempty" tf:"task_name,omitempty"`

	// Specifies the topic names separated by a comma of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the topics of the task.
	Topics *string `json:"topics,omitempty" tf:"topics,omitempty"`

	// Specifies the regular expression of topic name for the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the topics regular expression of the smart connect task.
	TopicsRegex *string `json:"topicsRegex,omitempty" tf:"topics_regex,omitempty"`
}

type KafkaSmartConnectTaskParameters struct {

	// Specifies the access key used to access the OBS bucket.
	// Changing this parameter will create a new resource.
	// Specifies the access key used to access the OBS bucket.
	// +kubebuilder:validation:Optional
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// Specifies the connector ID of the kafka instance.
	// Changing this parameter will create a new resource.
	// Specifies the connector id of the kafka instance.
	// +crossplane:generate:reference:type=github.com/huaweicloud/provider-huaweicloud/apis/kafka/v1alpha1.KafkaInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("connector_id",true)
	// +kubebuilder:validation:Optional
	ConnectorID *string `json:"connectorId,omitempty" tf:"connector_id,omitempty"`

	// Reference to a KafkaInstance in kafka to populate connectorId.
	// +kubebuilder:validation:Optional
	ConnectorIDRef *v1.Reference `json:"connectorIdRef,omitempty" tf:"-"`

	// Selector for a KafkaInstance in kafka to populate connectorId.
	// +kubebuilder:validation:Optional
	ConnectorIDSelector *v1.Selector `json:"connectorIdSelector,omitempty" tf:"-"`

	// Specifies the consumer strategy of the smart connect task.
	// Changing this parameter will create a new resource.
	// Value options:
	// Specifies the consumer strategy of the smart connect task.
	// +kubebuilder:validation:Optional
	ConsumerStrategy *string `json:"consumerStrategy,omitempty" tf:"consumer_strategy,omitempty"`

	// Specifies the deliver time interval of the smart connect task.
	// The value should be between 30 and 900. Changing this parameter will create a new resource.
	// Specifies the deliver time interval of the smart connect task.
	// +kubebuilder:validation:Optional
	DeliverTimeInterval *float64 `json:"deliverTimeInterval,omitempty" tf:"deliver_time_interval,omitempty"`

	// Specifies the destination file type of the smart connect task.
	// Only TEXT is supported. Changing this parameter will create a new resource.
	// Specifies the destination file type of the smart connect task.
	// +kubebuilder:validation:Optional
	DestinationFileType *string `json:"destinationFileType,omitempty" tf:"destination_file_type,omitempty"`

	// Specifies the destination type of the smart connect task.
	// Only OBS is supported. Changing this parameter will create a new resource.
	// Specifies the destination type of the smart connect task.
	// +kubebuilder:validation:Optional
	DestinationType *string `json:"destinationType,omitempty" tf:"destination_type,omitempty"`

	// Specifies the obs bucket name of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the obs bucket name of the smart connect task.
	// +kubebuilder:validation:Optional
	ObsBucketName *string `json:"obsBucketName,omitempty" tf:"obs_bucket_name,omitempty"`

	// Specifies the obs path of the smart connect task.
	// Obs path is separated by a slash. Changing this parameter will create a new resource.
	// Specifies the obs path of the smart connect task.
	// +kubebuilder:validation:Optional
	ObsPath *string `json:"obsPath,omitempty" tf:"obs_path,omitempty"`

	// Specifies the time directory format of the smart connect task.
	// Value options: yyyy, yyyy/MM, yyyy/MM/dd, yyyy/MM/dd/HH, yyyy/MM/dd/HH/mm.
	// Changing this parameter will create a new resource.
	// Specifies the partiton format of the smart connect task.
	// +kubebuilder:validation:Optional
	PartitionFormat *string `json:"partitionFormat,omitempty" tf:"partition_format,omitempty"`

	// Specifies the record delimiter of the smart connect task.
	// Value options: ,, ;, |, \n, "". Defaults to \n.
	// Changing this parameter will create a new resource.
	// Specifies the record delimiter of the smart connect task.
	// +kubebuilder:validation:Optional
	RecordDelimiter *string `json:"recordDelimiter,omitempty" tf:"record_delimiter,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used. Changing this parameter will create a new resource.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the secret access key used to access the OBS bucket.
	// Changing this parameter will create a new resource.
	// Specifies the secret access key used to access the OBS bucket.
	// +kubebuilder:validation:Optional
	SecretKeySecretRef v1.SecretKeySelector `json:"secretKeySecretRef" tf:"-"`

	// Specifies the source type of the smart connect task.
	// Only BLOB is supported. Changing this parameter will create a new resource.
	// Specifies the source type of the smart connect task.
	// +kubebuilder:validation:Optional
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// Specifies the name of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the name of the smart connect task.
	// +kubebuilder:validation:Optional
	TaskName *string `json:"taskName,omitempty" tf:"task_name,omitempty"`

	// Specifies the topic names separated by a comma of the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the topics of the task.
	// +kubebuilder:validation:Optional
	Topics *string `json:"topics,omitempty" tf:"topics,omitempty"`

	// Specifies the regular expression of topic name for the smart connect task.
	// Changing this parameter will create a new resource.
	// Specifies the topics regular expression of the smart connect task.
	// +kubebuilder:validation:Optional
	TopicsRegex *string `json:"topicsRegex,omitempty" tf:"topics_regex,omitempty"`
}

// KafkaSmartConnectTaskSpec defines the desired state of KafkaSmartConnectTask
type KafkaSmartConnectTaskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KafkaSmartConnectTaskParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KafkaSmartConnectTaskInitParameters `json:"initProvider,omitempty"`
}

// KafkaSmartConnectTaskStatus defines the observed state of KafkaSmartConnectTask.
type KafkaSmartConnectTaskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KafkaSmartConnectTaskObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KafkaSmartConnectTask is the Schema for the KafkaSmartConnectTasks API. ""
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type KafkaSmartConnectTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accessKey) || (has(self.initProvider) && has(self.initProvider.accessKey))",message="spec.forProvider.accessKey is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.consumerStrategy) || (has(self.initProvider) && has(self.initProvider.consumerStrategy))",message="spec.forProvider.consumerStrategy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deliverTimeInterval) || (has(self.initProvider) && has(self.initProvider.deliverTimeInterval))",message="spec.forProvider.deliverTimeInterval is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destinationType) || (has(self.initProvider) && has(self.initProvider.destinationType))",message="spec.forProvider.destinationType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.obsBucketName) || (has(self.initProvider) && has(self.initProvider.obsBucketName))",message="spec.forProvider.obsBucketName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.partitionFormat) || (has(self.initProvider) && has(self.initProvider.partitionFormat))",message="spec.forProvider.partitionFormat is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretKeySecretRef)",message="spec.forProvider.secretKeySecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourceType) || (has(self.initProvider) && has(self.initProvider.sourceType))",message="spec.forProvider.sourceType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.taskName) || (has(self.initProvider) && has(self.initProvider.taskName))",message="spec.forProvider.taskName is a required parameter"
	Spec   KafkaSmartConnectTaskSpec   `json:"spec"`
	Status KafkaSmartConnectTaskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KafkaSmartConnectTaskList contains a list of KafkaSmartConnectTasks
type KafkaSmartConnectTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KafkaSmartConnectTask `json:"items"`
}

// Repository type metadata.
var (
	KafkaSmartConnectTask_Kind             = "KafkaSmartConnectTask"
	KafkaSmartConnectTask_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KafkaSmartConnectTask_Kind}.String()
	KafkaSmartConnectTask_KindAPIVersion   = KafkaSmartConnectTask_Kind + "." + CRDGroupVersion.String()
	KafkaSmartConnectTask_GroupVersionKind = CRDGroupVersion.WithKind(KafkaSmartConnectTask_Kind)
)

func init() {
	SchemeBuilder.Register(&KafkaSmartConnectTask{}, &KafkaSmartConnectTaskList{})
}
