apiVersion: nat.huaweicloud.crossplane.io/v1alpha1
kind: PrivateGateway
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1alpha1/privategateway
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: ${var.gateway_name}
    spec: ${var.gateway_spec}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
