apiVersion: evs.huaweicloud.crossplane.io/v1alpha1
kind: SnapshotRollback
metadata:
  annotations:
    meta.upbound.io/example-id: evs/v1alpha1/snapshotrollback
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    snapshotIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: volume
