apiVersion: evs.huaweicloud.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: evs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: Daily backup
    name: snapshot-001
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: volume
