apiVersion: kafka.huaweicloud.crossplane.io/v1alpha1
kind: KafkaInstanceRebalanceLog
metadata:
  annotations:
    meta.upbound.io/example-id: kafka/v1alpha1/kafkainstancerebalancelog
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
